spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:udo
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
