spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:udo
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    web:
      pageable:
        default-page-size: 20

security:
  jwt:
    token:
      secret-key: f64114a23bd4db865b8e969ad6e3a3e9b88c8c41f0b63c775d6af530492053dcc6d80d40d34589de3ae3d8db2b2a7b26d609d9d962af0c9c3d6a65af777d9e69
      expire-length: 3600000
